# Generated by Django 3.2.6 on 2021-09-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correcoes',
            fields=[
                ('CR_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('CR_sku', models.CharField(max_length=50, null=True)),
                ('CR_prioridade', models.CharField(max_length=100, null=True)),
                ('CR_status', models.BooleanField()),
                ('CR_motivo_correcao_1', models.CharField(max_length=200, null=True)),
                ('CR_motivo_correcao_2', models.CharField(max_length=200, null=True)),
                ('CR_motivo_correcao_3', models.CharField(max_length=200, null=True)),
                ('CR_motivo_correcao_4', models.CharField(max_length=200, null=True)),
                ('CR_motivo_correcao_5', models.CharField(max_length=200, null=True)),
                ('CR_portal_ML_alaok', models.BooleanField()),
                ('CR_portal_ML_gea', models.BooleanField()),
                ('CR_portal_ML_kes', models.BooleanField()),
                ('CR_portal_ML_arrigo', models.BooleanField()),
                ('CR_portal_Magalu_gea', models.BooleanField()),
                ('CR_portal_Magalu_kes', models.BooleanField()),
                ('CR_portal_Magalu_kc', models.BooleanField()),
                ('CR_portal_Magalu_arrigo', models.BooleanField()),
                ('CR_portal_b2w_alaok', models.BooleanField()),
                ('CR_portal_b2w_kc', models.BooleanField()),
                ('CR_portal_b2w_jcma', models.BooleanField()),
                ('CR_portal_carrefour_alaok', models.BooleanField()),
                ('CR_portal_carrefour_gea', models.BooleanField()),
                ('CR_portal_carrefour_arrigo', models.BooleanField()),
                ('CR_portal_netshoes_alk', models.BooleanField()),
                ('CR_portal_netshoes_kes', models.BooleanField()),
                ('CR_portal_centauro_alaok', models.BooleanField()),
                ('CR_portal_olist_gea', models.BooleanField()),
                ('CR_portal_olist_arrigo', models.BooleanField()),
                ('CR_portal_leroy_kes', models.BooleanField()),
                ('CR_portal_madeiramadeira_kes', models.BooleanField()),
                ('CR_portal_madeiramadeira_arrigo', models.BooleanField()),
                ('CR_portal_amazon_kes', models.BooleanField()),
                ('CR_portal_amazon_kc', models.BooleanField()),
                ('CR_portal_amazon_arrigo', models.BooleanField()),
                ('CR_portal_cnova_kes', models.BooleanField()),
                ('CR_portal_cnova_arrigo', models.BooleanField()),
                ('CR_portal_shopee_kes', models.BooleanField()),
                ('CR_portal_aliexpress_arrigo', models.BooleanField()),
                ('CR_portal_mobly_kc', models.BooleanField()),
                ('CR_portal_elo7_arrigo', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('CR_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
