# Generated by Django 3.2.6 on 2021-09-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_correcoes_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correcoes',
            name='CR_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
