# Generated by Django 3.2.6 on 2021-10-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20210930_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='correcoes',
            name='CR_portal_Master',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='moveis',
            name='PM_cadastrado',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
