# Generated by Django 3.2.6 on 2021-10-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20211001_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moveis',
        ),
    ]
