# Generated by Django 3.2.6 on 2021-10-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0010_delete_moveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos_Arrigo',
            fields=[
                ('PA_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('PA_sku', models.CharField(max_length=100, null=True)),
                ('PA_modelo', models.CharField(max_length=100, null=True)),
                ('PA_titulo', models.CharField(max_length=200, null=True)),
                ('PA_custo', models.CharField(max_length=200, null=True)),
                ('PA_preco_venda', models.CharField(max_length=200, null=True)),
                ('PA_imagem1', models.CharField(max_length=250, null=True)),
                ('PA_imagem2', models.CharField(max_length=250, null=True)),
                ('PA_imagem3', models.CharField(max_length=250, null=True)),
                ('PA_imagem4', models.CharField(max_length=250, null=True)),
                ('PA_imagem5', models.CharField(max_length=250, null=True)),
                ('PA_imagem6', models.CharField(max_length=250, null=True)),
                ('PA_imagem7', models.CharField(max_length=250, null=True)),
                ('PA_imagem8', models.CharField(max_length=250, null=True)),
                ('PA_imagem9', models.CharField(max_length=250, null=True)),
                ('PA_imagem10', models.CharField(max_length=250, null=True)),
                ('PA_cor', models.CharField(max_length=100, null=True)),
                ('PA_verniz', models.CharField(max_length=100, null=True)),
                ('PA_tipo_tinta', models.CharField(max_length=100, null=True)),
                ('PA_escala_cor', models.CharField(max_length=100, null=True)),
                ('PA_material', models.CharField(max_length=100, null=True)),
                ('PA_material_especura', models.CharField(max_length=100, null=True)),
                ('PA_material_suporte', models.CharField(max_length=100, null=True)),
                ('PA_material_pintura_suporte', models.CharField(max_length=100, null=True)),
                ('PA_material_acabamento', models.CharField(max_length=100, null=True)),
                ('PA_localizacao', models.CharField(max_length=100, null=True)),
                ('PA_tipo_suporte', models.CharField(max_length=100, null=True)),
                ('PA_possui_pes', models.CharField(max_length=100, null=True)),
                ('PA_tipo_fixacao', models.CharField(max_length=100, null=True)),
                ('PA_envio', models.CharField(max_length=100, null=True)),
                ('PA_peso_suportado', models.FloatField()),
                ('PA_capacidade_garrafas', models.IntegerField()),
                ('PA_capacidade_copos', models.IntegerField()),
                ('PA_capacidade_tacas', models.IntegerField()),
                ('PA_quantidade_prateleiras', models.IntegerField()),
                ('PA_quantidade_suportes', models.IntegerField()),
                ('PA_quantidade_gavetas', models.IntegerField()),
                ('PA_peso', models.FloatField()),
                ('PA_medida_externa_altura', models.FloatField()),
                ('PA_medida_externa_largura', models.FloatField()),
                ('PA_medida_externa_profundidade', models.FloatField()),
                ('PA_quantidade_parafusos_fixacao', models.IntegerField()),
                ('PA_medidas_internas', models.TextField()),
            ],
        ),
    ]
