# Generated by Django 3.2.6 on 2021-10-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0011_produtos_arrigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='opcao_cor',
            fields=[
                ('OC_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OC_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_envio',
            fields=[
                ('OE_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OE_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_escala_cor',
            fields=[
                ('OES_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OES_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_localizacao',
            fields=[
                ('OL_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OL_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_material',
            fields=[
                ('OM_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OM_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_material_acabamento',
            fields=[
                ('OMA_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OMA_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_material_especura',
            fields=[
                ('OME_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OME_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_material_pintura_suporte',
            fields=[
                ('OMPS_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OMPS_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_material_suporte',
            fields=[
                ('OMS_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OMS_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_possui_pes',
            fields=[
                ('OPP_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OPP_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_tipo_fixacao',
            fields=[
                ('OTF_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OTF_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_tipo_suporte',
            fields=[
                ('OTS_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OTS_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_tipo_tinta',
            fields=[
                ('OTT_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OTT_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='opcao_verniz',
            fields=[
                ('OV_ID', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('OV_valor', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produtos_arrigo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='produtos_arrigo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
